### ISSUE TITLE
Fix memory leak

### ISSUE THREAD

**Issue by nullsoftware** [malatindez/GMTK2023#5]
![image](https://github.com/malatindez/GMTK2023/assets/71794059/6c1824c6-7045-4b72-9b3c-05cc011c11bc)

**Comment by malatindez** [comment]
Not a bug nor a leak. This is related to the allocation of `_visibilityMaskRayData` `ComputeBuffer` in `VisibilityManager.cs`. 

It is later used and destroyed with `VisibilityManager` component.
